#!/usr/bin/env python3
#-*- coding: UTF-8 -*-

import rospy 
from ros_opencv.msg import ros_red

rospy.init_node("subscriber", anonymous = True)

def function(data):

    rospy.loginfo("[INFO].. center is calculated: (%.2f, %.2f)", data.x1, data.y1)


rospy.Subscriber("center_topic", ros_red, function)
rospy.spin()
